http:
  middlewares:
    my-fail2ban:
      plugin:
        fail2ban:
          allowlist:
            ip: ::1,127.0.0.1,REPLACE_WITH_ALLOWED_IP_OR_FQDN_FROM_DYNAMIC_DNS_SERVICE
          rules:
            bantime: 15m
            enabled: "true"
            findtime: 5m
            maxretry: "20"
            statuscode: 400,401,403-499

